remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Aves Order Classifier
description: An Image Classification API that classifies all known bird species according to their Order name.

author:
  name: Mehrab Mashrafi

stylesheets:
  - /assets/css/custom.css
javascripts:
  - /assets/js/custom.js
